[project]
name = "ai-advanced-halcyon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "lab>=8.4",
]
